import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Create demo users
  const hashedPassword = await bcrypt.hash('demo1234', 12)

  const user1 = await prisma.user.upsert({
    where: { email: 'demo@kothanepal.com' },
    update: {},
    create: {
      name: 'Ram Prasad Sharma',
      email: 'demo@kothanepal.com',
      password: hashedPassword,
      phone: '9841234567',
      city: 'kathmandu',
      bio: 'Experienced landlord with properties in Kathmandu valley.',
      isVerified: true,
      isLandlord: true,
    },
  })

  const user2 = await prisma.user.upsert({
    where: { email: 'sita@example.com' },
    update: {},
    create: {
      name: 'Sita Devi Thapa',
      email: 'sita@example.com',
      password: hashedPassword,
      phone: '9851234567',
      city: 'pokhara',
      bio: 'Property owner in Pokhara. Clean and furnished rooms available.',
      isVerified: true,
      isLandlord: true,
    },
  })

  const user3 = await prisma.user.upsert({
    where: { email: 'hari@example.com' },
    update: {},
    create: {
      name: 'Hari Bahadur KC',
      email: 'hari@example.com',
      password: hashedPassword,
      phone: '9861234567',
      city: 'kathmandu',
      isLandlord: true,
    },
  })

  console.log('Users created')

  // Create listings
  const listings = [
    {
      title: 'Furnished 1BHK Flat Near Thamel, Kathmandu',
      description: 'Beautiful fully furnished 1BHK flat in the heart of Thamel. Perfect for single professionals or couples. The flat has modern amenities including WiFi, 24-hour water supply, and parking space. Located just 5 minutes walk from Thamel Chowk. Nearby restaurants, banks, and shops. Quiet neighborhood with good security.',
      price: 18000,
      negotiable: true,
      deposit: 36000,
      listingType: 'flat',
      roomType: '1bhk',
      furnishing: 'furnished',
      availableFrom: new Date('2024-01-01'),
      minStay: '6 months',
      city: 'kathmandu',
      area: 'Thamel',
      landmark: 'Near Thamel Chowk',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 2,
      totalFloors: 4,
      squareFeet: 650,
      wifi: true,
      parking: true,
      water24hrs: true,
      electricity: true,
      generator: true,
      kitchen: true,
      tv: true,
      fridge: true,
      security: true,
      preferredGender: 'any',
      cookingAllowed: true,
      visitorsAllowed: true,
      waterBillIncluded: true,
      internetIncluded: true,
      isActive: true,
      isFeatured: true,
      views: 234,
      userId: user1.id,
    },
    {
      title: 'Single Room for Rent in Baluwatar - Walking Distance to Maharajgunj',
      description: 'Cozy single room available in a quiet residential area of Baluwatar. Ideal for working professionals or students. The room comes with attached bathroom. The landlord is friendly and lives in the same building. Easy access to Maharajgunj and Lainchaur.',
      price: 7500,
      negotiable: false,
      deposit: 15000,
      listingType: 'room',
      roomType: 'single',
      furnishing: 'semi-furnished',
      availableFrom: new Date(),
      minStay: '3 months',
      city: 'kathmandu',
      area: 'Baluwatar',
      landmark: 'Near Baluwatar Police Headquarters',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 1,
      totalFloors: 3,
      wifi: true,
      water24hrs: true,
      electricity: true,
      kitchen: true,
      preferredGender: 'male',
      preferredOccupation: 'working',
      smokingAllowed: false,
      alcoholAllowed: false,
      cookingAllowed: true,
      visitorsAllowed: false,
      waterBillIncluded: true,
      isActive: true,
      isFeatured: false,
      views: 89,
      userId: user1.id,
    },
    {
      title: 'Spacious 2BHK Apartment in Lakeside, Pokhara',
      description: 'Beautiful 2BHK apartment with stunning lake view from the balcony. Located in the prime tourist area of Lakeside, Pokhara. The apartment is fully furnished with all modern amenities. Perfect for families or working couples. The building has 24-hour security and backup power.',
      price: 22000,
      negotiable: true,
      deposit: 44000,
      listingType: 'flat',
      roomType: '2bhk',
      furnishing: 'furnished',
      availableFrom: new Date(),
      minStay: '6 months',
      city: 'pokhara',
      area: 'Lakeside',
      landmark: 'Near Phewa Lake',
      bedrooms: 2,
      bathrooms: 2,
      floorNumber: 3,
      totalFloors: 5,
      squareFeet: 950,
      wifi: true,
      parking: true,
      water24hrs: true,
      electricity: true,
      generator: true,
      ac: true,
      kitchen: true,
      tv: true,
      fridge: true,
      washingMachine: true,
      security: true,
      cctv: true,
      lift: true,
      rooftop: true,
      preferredGender: 'any',
      preferredOccupation: 'any',
      petsAllowed: false,
      cookingAllowed: true,
      visitorsAllowed: true,
      waterBillIncluded: true,
      electricBillIncluded: false,
      internetIncluded: true,
      isActive: true,
      isFeatured: true,
      views: 456,
      userId: user2.id,
    },
    {
      title: 'PG Accommodation for Girls - Baneshwor, Kathmandu',
      description: 'Safe and secure PG accommodation exclusively for girls/women. Located in Baneshwor, close to Tribhuvan University and various colleges. Meals available on request. The PG has strict security with CCTV cameras and security guard. Three meals per day can be arranged at additional cost.',
      price: 9000,
      deposit: 18000,
      listingType: 'pg',
      roomType: 'shared',
      furnishing: 'furnished',
      availableFrom: new Date(),
      minStay: '1 month',
      city: 'kathmandu',
      area: 'Baneshwor',
      landmark: 'Near Baneshwor Multiple Campus',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 2,
      totalFloors: 3,
      wifi: true,
      water24hrs: true,
      electricity: true,
      tv: true,
      security: true,
      cctv: true,
      kitchen: true,
      laundry: true,
      preferredGender: 'female',
      preferredOccupation: 'student',
      petsAllowed: false,
      smokingAllowed: false,
      alcoholAllowed: false,
      visitorsAllowed: false,
      cookingAllowed: false,
      waterBillIncluded: true,
      electricBillIncluded: true,
      internetIncluded: true,
      isActive: true,
      isFeatured: true,
      views: 312,
      userId: user1.id,
    },
    {
      title: 'Room for Rent - Looking for Flatmate in Sanepa',
      description: 'Looking for a flatmate to share a 2BHK apartment in Sanepa, Lalitpur. Currently one person living and looking for a compatible flatmate. The apartment is on the 3rd floor of a peaceful building. Rent is split equally. Must be clean, respectful, and have a regular job.',
      price: 11000,
      listingType: 'roommate',
      roomType: 'single',
      furnishing: 'semi-furnished',
      availableFrom: new Date(),
      minStay: '6 months',
      city: 'lalitpur',
      area: 'Sanepa',
      landmark: 'Near Sanepa Chowk',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 3,
      totalFloors: 4,
      wifi: true,
      water24hrs: true,
      electricity: true,
      kitchen: true,
      preferredGender: 'male',
      preferredOccupation: 'working',
      smokingAllowed: false,
      cookingAllowed: true,
      visitorsAllowed: true,
      isActive: true,
      views: 178,
      userId: user3.id,
    },
    {
      title: 'Studio Apartment Near Civil Service Hospital, Minbhawan',
      description: 'Compact studio apartment perfect for a single working professional. Located near Civil Service Hospital and Minbhawan. The studio has a separate bathroom, small kitchenette, and fits a single bed comfortably. Very close to public transport.',
      price: 12000,
      negotiable: false,
      deposit: 24000,
      listingType: 'flat',
      roomType: 'studio',
      furnishing: 'semi-furnished',
      availableFrom: new Date(),
      city: 'kathmandu',
      area: 'New Baneshwor',
      landmark: 'Near Civil Service Hospital',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 1,
      totalFloors: 5,
      squareFeet: 350,
      wifi: true,
      water24hrs: true,
      electricity: true,
      kitchen: true,
      preferredGender: 'any',
      preferredOccupation: 'working',
      cookingAllowed: true,
      visitorsAllowed: true,
      isActive: true,
      views: 145,
      userId: user1.id,
    },
    {
      title: '3BHK House for Rent in Bhaktapur - Near Durbar Square',
      description: 'Traditional Newari style 3BHK house available for rent near the iconic Bhaktapur Durbar Square. The house is 3 floors with open courtyard. Very spacious and ideal for a family. The house has solar water heating, rainwater harvesting, and organic kitchen garden. Peaceful environment.',
      price: 28000,
      negotiable: true,
      deposit: 56000,
      listingType: 'house',
      roomType: '3bhk',
      furnishing: 'unfurnished',
      availableFrom: new Date(),
      minStay: '1 year',
      city: 'bhaktapur',
      area: 'Durbar Square',
      landmark: 'Near Bhaktapur Durbar Square',
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1800,
      water24hrs: true,
      electricity: true,
      solarPower: true,
      generator: false,
      parking: true,
      kitchen: true,
      garden: true,
      rooftop: true,
      preferredGender: 'any',
      preferredOccupation: 'family',
      petsAllowed: true,
      cookingAllowed: true,
      visitorsAllowed: true,
      waterBillIncluded: false,
      electricBillIncluded: false,
      isActive: true,
      isFeatured: true,
      views: 267,
      userId: user2.id,
    },
    {
      title: 'Furnished Room with Attached Bathroom - Lazimpat',
      description: 'Well-maintained furnished room in a prime location of Lazimpat. Attached bathroom, wardrobe, study table, and bed included. Ideal for embassy staff, NGO workers, or professionals. The building has 24-hour water supply, internet, and backup generator. Very safe and quiet neighborhood.',
      price: 15000,
      negotiable: false,
      deposit: 30000,
      listingType: 'room',
      roomType: 'master',
      furnishing: 'furnished',
      availableFrom: new Date(),
      city: 'kathmandu',
      area: 'Lazimpat',
      bedrooms: 1,
      bathrooms: 1,
      floorNumber: 2,
      totalFloors: 3,
      wifi: true,
      water24hrs: true,
      electricity: true,
      generator: true,
      tv: true,
      fridge: true,
      security: true,
      preferredGender: 'any',
      preferredOccupation: 'working',
      smokingAllowed: false,
      cookingAllowed: false,
      visitorsAllowed: true,
      waterBillIncluded: true,
      electricBillIncluded: true,
      internetIncluded: true,
      isActive: true,
      views: 198,
      userId: user3.id,
    },
  ]

  for (const listing of listings) {
    await prisma.listing.create({ data: listing })
  }

  console.log(`Created ${listings.length} listings`)
  console.log('\n✅ Database seeded successfully!')
  console.log('\nDemo accounts:')
  console.log('  Email: demo@kothanepal.com')
  console.log('  Password: demo1234')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
